---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: Ajoutez des utilisateurs à votre système Astra Control Center et supprimez les utilisateurs qui ne devraient plus avoir accès au système. 
---
= Gérer les utilisateurs
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Vous pouvez ajouter, supprimer et modifier les utilisateurs de votre installation Astra Control Center à l'aide de l'interface utilisateur du Centre de contrôle Astra. Vous pouvez utiliser l'interface utilisateur Astra ou https://docs.netapp.com/us-en/astra-automation/index.html["API de contrôle Astra"^] pour gérer les utilisateurs.



== Ajouter des utilisateurs

Les propriétaires et administrateurs de comptes peuvent ajouter d'autres utilisateurs à l'installation d'Astra Control Center.

.Étapes
. Dans la zone de navigation *gérer votre compte*, sélectionnez *compte*.
. Sélectionnez l'onglet *utilisateurs*.
. Sélectionnez *Ajouter utilisateur*.
. Entrez le nom de l'utilisateur, son adresse e-mail et son mot de passe temporaire.
+
L'utilisateur doit modifier le mot de passe lors de sa première connexion.

. Sélectionnez un rôle d'utilisateur avec les autorisations système appropriées.
+
Chaque rôle offre les autorisations suivantes :

+
** Un *Viewer* peut afficher les ressources.
** Un *membre* dispose des autorisations de rôle Viewer et peut gérer les applications et les clusters, mais ne peut pas annuler la gestion des applications ou des clusters, ni supprimer des instantanés ou des sauvegardes.
** Un *Admin* dispose des autorisations de rôle de membre et peut ajouter et supprimer d'autres utilisateurs, à l'exception du propriétaire.
** Un *propriétaire* possède des autorisations de rôle d'administrateur et peut ajouter et supprimer des comptes d'utilisateur.


. Sélectionnez *Ajouter*.




== Gérer les mots de passe

Vous pouvez gérer les mots de passe des comptes utilisateur dans Astra Control Center.



=== Changer votre mot de passe

Vous pouvez modifier le mot de passe de votre compte utilisateur à tout moment.

.Étapes
. Sélectionnez l'icône utilisateur en haut à droite de l'écran.
. Sélectionnez *Profile*.
. Sélectionnez la liste déroulante *actions* et sélectionnez *Modifier le mot de passe*.
. Saisissez un mot de passe conforme aux exigences de mot de passe.
. Saisissez à nouveau le mot de passe pour le confirmer.
. Sélectionnez *changer mot de passe*.




=== Réinitialiser le mot de passe d'un autre utilisateur

Si votre compte dispose des autorisations de rôle Administrateur ou propriétaire, vous pouvez réinitialiser les mots de passe des autres comptes utilisateur ainsi que les vôtres. Lorsque vous réinitialisez un mot de passe, vous attribuez un mot de passe temporaire que l'utilisateur devra modifier lors de la connexion.

.Étapes
. Dans la zone de navigation *gérer votre compte*, sélectionnez *compte*.
. Dans l'onglet *utilisateurs*, sélectionnez la liste déroulante dans la colonne *état* de l'utilisateur.
. Sélectionnez *Réinitialiser le mot de passe*.
. Saisissez un mot de passe temporaire conforme aux exigences de mot de passe.
. Saisissez à nouveau le mot de passe pour le confirmer.
+

NOTE: Lors de la prochaine connexion de l'utilisateur, l'utilisateur est invité à modifier le mot de passe.

. Sélectionnez *Réinitialiser le mot de passe*.




== Modifier le rôle d'un utilisateur

Les utilisateurs ayant le rôle propriétaire peuvent modifier le rôle de tous les utilisateurs, tandis que les utilisateurs disposant du rôle Administrateur peuvent modifier le rôle des utilisateurs qui ont le rôle Administrateur, membre ou Visionneuse.

.Étapes
. Dans la zone de navigation *gérer votre compte*, sélectionnez *compte*.
. Dans l'onglet *utilisateurs*, sélectionnez la liste déroulante dans la colonne *rôle* de l'utilisateur.
. Sélectionnez un nouveau rôle, puis sélectionnez *changer le rôle* lorsque vous y êtes invité.


Astra Control Center met à jour les autorisations de l'utilisateur en fonction du nouveau rôle que vous avez sélectionné.



== Supprimer des utilisateurs

Les utilisateurs disposant du rôle propriétaire ou administrateur peuvent à tout moment supprimer d'autres utilisateurs du compte.

.Étapes
. Dans la zone de navigation *gérer votre compte*, sélectionnez *compte*.
. Dans l'onglet *Users*, cochez la case de la ligne de chaque utilisateur que vous souhaitez supprimer.
. Sélectionnez *actions* et sélectionnez *Supprimer utilisateur/s*.
. Lorsque vous y êtes invité, confirmez la suppression en saisissant le mot "supprimer", puis sélectionnez *Oui, Supprimer l'utilisateur*.


Astra Control Center supprime l'utilisateur du compte.
