---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Décrit comment retirer le centre de contrôle Astra et le conducteur du centre de contrôle Astra. 
---
= Désinstaller Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Vous devrez peut-être retirer les composants du centre de contrôle Astra si vous effectuez une mise à niveau d'un essai vers une version complète du produit. Pour déposer le centre de commande Astra et le conducteur du centre de commande Astra, exécuter les commandes décrites dans cette procédure dans l'ordre.

.Ce dont vous avez besoin
* Utilisez l'interface utilisateur d'Astra Control Center pour tout supprimer link:../use/unmanage.html#stop-managing-compute["clusters"].


.Étapes
. Supprimer Astra Control Center. L'exemple de commande suivant est basé sur une installation par défaut. Modifiez la commande si vous avez créé des configurations personnalisées.
+
[listing]
----
kubectl delete -f astra_control_center_min.yaml -n netapp-acc
----
+
Résultat :

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Utiliser la commande suivante pour supprimer le `netapp-acc` espace de noms :
+
[listing]
----
kubectl delete ns netapp-acc
----
+
Résultat :

+
[listing]
----
namespace "netapp-acc" deleted
----
. Utiliser la commande suivante pour supprimer les composants du système de l'opérateur Astra Control Center :
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Résultat :

+
[listing]
----
namespace "netapp-acc-operator" deleted
customresourcedefinition.apiextensions.k8s.io "astracontrolcenters.astra.netapp.io" deleted
role.rbac.authorization.k8s.io "acc-operator-leader-election-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-manager-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-metrics-reader" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-proxy-role" deleted
rolebinding.rbac.authorization.k8s.io "acc-operator-leader-election-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-manager-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-proxy-rolebinding" deleted
configmap "acc-operator-manager-config" deleted
service "acc-operator-controller-manager-metrics-service" deleted
deployment.apps "acc-operator-controller-manager" deleted
----




== Trouvez plus d'informations

* link:../release-notes/known-issues.html["Problèmes connus de désinstallation"]

