---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters 
summary: Commencez à utiliser Astra Control Center en vérifiant la prise en charge de vos clusters Kubernetes, de vos applications et de votre navigateur Web. 
---
= Exigences du centre de contrôle Astra
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Commencez par vérifier que votre environnement opérationnel, vos clusters d'applications, vos applications, vos licences et votre navigateur Web sont prêts.



== De l'environnement opérationnel

Astra Control Center requiert l'un des types d'environnements opérationnels suivants :

* Red Hat OpenShift Container Platform 4.6.8, 4.7 ou 4.8
* Rancher 2.5
* Kubernetes 1.19 à 1.21 (dont 1.21.x)


Assurez-vous que l'environnement d'exploitation que vous choisissez d'héberger est conforme aux exigences de base en matière de ressources décrites dans la documentation officielle de l'environnement. Outre les exigences de l'environnement en matière de ressources, Astra Control Center requiert les ressources suivantes :

|===
| Composant | Conditions requises 


| Capacité de stockage ONTAP interne | 300 Go au moins disponibles 


| Nœuds worker | Au moins 3 nœuds workers au total, avec 4 cœurs de processeurs et 12 Go de RAM chacun 


| Équilibrage de la charge | Type de service « LoadBalancer » disponible pour que le trafic d'entrée soit envoyé aux services du cluster d'environnement opérationnel 


| Résolution du FQDN | Méthode permettant de pointer le FQDN de Astra Control Center vers l'adresse IP à charge équilibrée 


| Astra Trident  a| 
* Astra Trident 21.04 ou version ultérieure installé et configuré si NetApp ONTAP version 9.5 ou ultérieure sera utilisé comme système de stockage back-end
* Astra Trident 21.10.1 ou version ultérieure installé et configuré en cas d'utilisation de la version préliminaire du magasin de données d'Astra comme système de stockage back-end


|===

NOTE: De telles exigences supposent que Astra Control Center est la seule application qui s'exécute dans l'environnement opérationnel. Si l'environnement exécute des applications supplémentaires, ajustez ces exigences minimales en conséquence.

* *Registre d'images*: Vous devez avoir un registre d'images privé Docker existant à laquelle vous pouvez pousser les images de construction d'Astra Control Center. Vous devez fournir l'URL du registre d'images où vous allez télécharger les images.
* *Configuration de l'Astra Trident / ONTAP* : le Centre de contrôle Astra requiert la création et la définition d'une classe de stockage comme classe de stockage par défaut. Le centre de contrôle Astra prend en charge les pilotes ONTAP suivants fournis par Astra Trident :
+
** ontap-nas
** ontap-san
** ontap-san-économie




[NOTE]
====
Lors du clonage d'applications dans les environnements OpenShift, Astra Control Center doit permettre à OpenShift de monter des volumes et de modifier la propriété des fichiers. Pour cela, il faut configurer une policy d'exportation de volume ONTAP afin de permettre ces opérations. Pour ce faire, utilisez les commandes suivantes :

. `export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -superuser sys`
. `export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -anon 65534`


====

NOTE: Si vous prévoyez d'ajouter un deuxième environnement opérationnel OpenShift comme ressource de calcul gérée, vous devez vous assurer que la fonctionnalité Snapshot de volume Astra Trident est activée. Pour activer et tester des copies Snapshot de volumes avec Astra Trident, https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["Consultez les instructions officielles de l'Astra Trident"^].



== Configuration requise en cluster des applications

Astra Control Center a les exigences suivantes pour les clusters que vous prévoyez de gérer à partir d'Astra Control Center. Ces exigences s'appliquent également si le cluster que vous prévoyez de gérer est le cluster d'environnement opérationnel qui héberge Astra Control Center.

* La version la plus récente de Kubernetes https://kubernetes-csi.github.io/docs/snapshot-controller.html["composant de snapshot-controller"^] est installé
* Découvrez Astra Trident https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["objet volumesnapshotclass"^] a été défini par un administrateur
* Une classe de stockage Kubernetes par défaut existe sur le cluster
* Au moins une classe de stockage est configurée pour utiliser Astra Trident



NOTE: Votre cluster d'applications doit disposer d'un `kubeconfig.yaml` fichier qui définit un seul _context_ element. Consultez la documentation Kubernetes sur https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["informations sur la création de fichiers kubeconfig"^].


NOTE: Lors de la gestion des clusters d'applications dans un environnement Rancher, modifiez le contexte par défaut du cluster d'applications dans `kubeconfig` Fichier fourni par Rancher pour utiliser un contexte de plan de contrôle au lieu du contexte de serveur API Rancher. La charge est réduite sur le serveur API Rancher et les performances sont améliorées.



== De gestion des applications

Astra Control présente les exigences de gestion des applications suivantes :

* *Licence* : pour gérer des applications à l'aide d'Astra Control Center, vous devez disposer d'une licence Astra Control Center.
* *Espaces de noms* : Astra Control exige qu'une application ne couvre pas plus d'un seul espace de noms, mais qu'un espace de noms peut contenir plus d'une application.
* *StorageClass* : si vous installez explicitement une application avec une classe de stockage et que vous devez cloner l'application, le cluster cible pour l'opération de clonage doit avoir la classe de stockage spécifiée à l'origine. Le clonage d'une application avec une classe de stockage explicitement définie sur un cluster ne disposant pas de la même classe de stockage échouera.
* *Ressources Kubernetes* : les applications qui utilisent des ressources Kubernetes non collectées par Astra Control peuvent ne pas disposer de fonctionnalités complètes de gestion des données d'application. Astra Control collecte les ressources Kubernetes suivantes :
+
** ClusterRole
** ClusterRoleBinding
** ConfigMap
** CustomResourceDefinition
** Ressource CustomResource
** Ensemble de démonstrations
** Déploiement
** Déploiement.Config
** Entrée
** MutatingWebhook
** Demande de volume persistant
** Pod
** Et de réplication
** RoleBinding
** Rôle
** Itinéraire
** Secret
** Service
** Compte de service
** StatefulSet
** ValidétingWebhook






=== Méthodes d'installation d'applications prises en charge

Astra Control prend en charge les méthodes d'installation d'application suivantes :

* *Fichier manifeste* : Astra Control prend en charge les applications installées à partir d'un fichier manifeste utilisant kubectl. Par exemple :
+
[listing]
----
kubectl apply -f myapp.yaml
----
* *Helm 3* : si vous utilisez Helm pour installer des applications, Astra Control nécessite Helm version 3. La gestion et le clonage des applications installées avec Helm 3 (ou mises à niveau de Helm 2 à Helm 3) sont entièrement pris en charge. La gestion des applications installées avec Helm 2 n'est pas prise en charge.
* *Applications déployées par l'opérateur* : Astra Control prend en charge les applications installées avec des opérateurs de l'espace de noms. Les applications suivantes ont été validées pour ce modèle d'installation :
+
** https://github.com/k8ssandra/cass-operator/tree/v1.7.1["Apache K8ssandra"^]
** https://github.com/jenkinsci/kubernetes-operator["IC Jenkins"^]
** https://github.com/percona/percona-xtradb-cluster-operator["Cluster Percona XtraDB"^]





NOTE: Un opérateur et l'application qu'il installe doivent utiliser le même espace de noms ; vous devrez peut-être modifier le fichier .yaml de déploiement pour que l'opérateur s'assure que c'est le cas.



== Accès à Internet

Vous devez déterminer si vous avez un accès externe à Internet. Si ce n'est pas le cas, certaines fonctionnalités peuvent être limitées, comme la réception de données de surveillance et de metrics depuis NetApp Cloud Insights ou l'envoi de packs de support au https://mysupport.netapp.com/site/["Site de support NetApp"^].



== Licence

Astra Control Center requiert une licence Astra Control Center pour bénéficier de toutes les fonctionnalités. Obtenez une licence d'évaluation ou une licence complète auprès de NetApp. Sans licence, vous ne pourrez pas :

* Définir des applications personnalisées
* Créer des snapshots ou des clones d'applications existantes
* Configuration des règles de protection des données


Si vous voulez essayer Astra Control Center, vous pouvez link:setup_overview.html#add-a-full-or-evaluation-license["utilisez une licence d'essai gratuite de 90 jours"].



== Type de service « LoadBalancer » pour les clusters Kubernetes sur site

Astra Control Center utilise un service de type "LoadBalancer" (svc/trafik dans l'espace de noms du Centre de contrôle Astra), et exige qu'il se voit attribuer une adresse IP externe accessible. Si des équilibreurs de charge sont autorisés dans votre environnement et que vous n'en avez pas encore configuré, vous pouvez utiliser https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_LB_MetalLB.html#installing-the-metallb-load-balancer["MetalLB"^] Pour attribuer automatiquement une adresse IP externe au service. Dans la configuration du serveur DNS interne, pointez le nom DNS choisi pour Astra Control Center vers l'adresse IP à équilibrage de charge.



== Configuration réseau requise

L'environnement opérationnel qui héberge le centre de contrôle Astra communique avec les ports TCP suivants. Veillez à ce que ces ports soient autorisés par le biais de pare-feu et configurez des pare-feu pour autoriser tout trafic de sortie HTTPS provenant du réseau Astra. Certains ports nécessitent une connectivité entre l'environnement hébergeant le centre de contrôle Astra et chaque cluster géré (le cas échéant).

|===
| Source | Destination | Port | Protocole | Objectif 


| PC client | Centre de contrôle Astra | 443 | HTTPS | Accès à l'interface utilisateur/à l'API : assurez-vous que ce port est ouvert à la fois entre le cluster hébergeant Astra Control Center et chaque cluster géré 


| Consommateurs de metrics | Nœud de travail Astra Control Center | 9090 | HTTPS | Communication de données de metrics : assurez-vous que chaque cluster géré peut accéder à ce port sur le cluster hébergeant Astra Control Center (communication bidirectionnelle requise). 


| Centre de contrôle Astra | Service Cloud Insights hébergé (https://cloudinsights.netapp.com)[] | 443 | HTTPS | Communication avec Cloud Insights 


| Centre de contrôle Astra | Fournisseur de compartiments de stockage Amazon S3 (https://my-bucket.s3.us-west-2.amazonaws.com/)[] | 443 | HTTPS | Communications de stockage Amazon S3 


| Centre de contrôle Astra | Active IQ de NetApp (https://activeiq.solidfire.com)[] | 443 | HTTPS | Communication avec NetApp ActiveIQ 
|===


== Navigateurs Web pris en charge

Astra Control Center prend en charge les versions récentes de Firefox, Safari et Chrome avec une résolution minimale de 1280 x 720.



== Et la suite

Afficher le link:quick-start.html["démarrage rapide"] présentation.
